<?php

namespace App\Tests\Unit\Security;

use App\Entity\Conference;
use App\Entity\User;
use App\Enum\EventStatus;
use App\Security\Voter\EventVoter;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Security\Core\Authentication\Token\NullToken;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface;
use Symfony\Component\Security\Core\Authorization\Voter\VoterInterface;

final class EventVoterTest extends TestCase
{
    public function testAnonymousCanViewPublishedEventOnly(): void
    {
        $voter = $this->createVoter();

        self::assertSame(VoterInterface::ACCESS_GRANTED, $voter->vote(new NullToken(), $this->event(EventStatus::Published), [EventVoter::VIEW]));
        self::assertSame(VoterInterface::ACCESS_DENIED, $voter->vote(new NullToken(), $this->event(EventStatus::Draft), [EventVoter::VIEW]));
        self::assertSame(VoterInterface::ACCESS_DENIED, $voter->vote(new NullToken(), $this->event(EventStatus::Published), [EventVoter::EDIT]));
    }

    public function testOrganizerCanEditOwnEvent(): void
    {
        $organizer = $this->user(1);
        $event = $this->event(EventStatus::Draft, $organizer);

        self::assertSame(VoterInterface::ACCESS_GRANTED, $this->createVoter()->vote($this->token($organizer), $event, [EventVoter::EDIT]));
        self::assertSame(VoterInterface::ACCESS_GRANTED, $this->createVoter()->vote($this->token($organizer), $event, [EventVoter::VIEW]));
    }

    public function testAnotherOrganizerCannotEdit(): void
    {
        $event = $this->event(EventStatus::Published, $this->user(1));

        self::assertSame(VoterInterface::ACCESS_DENIED, $this->createVoter()->vote($this->token($this->user(2)), $event, [EventVoter::EDIT]));
        self::assertSame(VoterInterface::ACCESS_DENIED, $this->createVoter()->vote($this->token($this->user(2)), $event, [EventVoter::DELETE]));
    }

    public function testAdminCanEditAnyEvent(): void
    {
        $event = $this->event(EventStatus::Draft, $this->user(1));

        $voter = $this->createVoter(isAdmin: true);

        self::assertSame(VoterInterface::ACCESS_GRANTED, $voter->vote($this->token($this->user(2)), $event, [EventVoter::DELETE]));
    }

    public function testAbstainsOnUnsupportedAttributeOrSubject(): void
    {
        $voter = $this->createVoter();

        self::assertSame(VoterInterface::ACCESS_ABSTAIN, $voter->vote(new NullToken(), $this->event(EventStatus::Draft), ['OTHER']));
        self::assertSame(VoterInterface::ACCESS_ABSTAIN, $voter->vote(new NullToken(), new \stdClass(), [EventVoter::EDIT]));
    }

    private function createVoter(bool $isAdmin = false): EventVoter
    {
        $decisionManager = $this->createStub(AccessDecisionManagerInterface::class);
        $decisionManager->method('decide')->willReturn($isAdmin);

        return new EventVoter($decisionManager);
    }

    private function user(int $id): User
    {
        $user = (new User())->setEmail("user{$id}@example.com");
        // The id is generated by Doctrine: set it by reflection for this unit test
        (new \ReflectionProperty(User::class, 'id'))->setValue($user, $id);

        return $user;
    }

    private function event(EventStatus $status, ?User $organizer = null): Conference
    {
        return (new Conference())
            ->setStatus($status)
            ->setOrganizer($organizer ?? $this->user(99));
    }

    private function token(User $user): TokenInterface
    {
        return new UsernamePasswordToken($user, 'api', $user->getRoles());
    }
}
