<?php

namespace App\Entity;

use App\Enum\EventStatus;
use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;

/**
 * Single Table Inheritance: conferences and workshops share the "event" table,
 * the "type" column tells Doctrine which subclass to hydrate.
 */
#[ORM\Entity(repositoryClass: EventRepository::class)]
#[ORM\InheritanceType('SINGLE_TABLE')]
#[ORM\DiscriminatorColumn(name: 'type', type: 'string', length: 20)]
#[ORM\DiscriminatorMap([
    Conference::TYPE => Conference::class,
    Workshop::TYPE => Workshop::class,
])]
#[ORM\Index(columns: ['status', 'starts_at'])]
abstract class Event extends TimestampableEntity
{
    #[ORM\Column(length: 150)]
    #[Groups(['event:list', 'event:read', 'registration:read'])]
    private ?string $title = null;

    /** Generated by App\Doctrine\Listener\EventSlugListener. */
    #[ORM\Column(length: 180, unique: true)]
    #[Groups(['event:list', 'event:read', 'registration:read'])]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups(['event:read'])]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    #[Groups(['event:list', 'event:read', 'registration:read'])]
    private ?\DateTimeImmutable $startsAt = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    #[Groups(['event:list', 'event:read', 'registration:read'])]
    private ?\DateTimeImmutable $endsAt = null;

    #[ORM\Column(length: 255)]
    #[Groups(['event:list', 'event:read', 'registration:read'])]
    private ?string $location = null;

    /** Maximum number of participants, null means unlimited. */
    #[ORM\Column(nullable: true)]
    #[Groups(['event:list', 'event:read'])]
    private ?int $capacity = null;

    #[ORM\Column(length: 20, enumType: EventStatus::class)]
    #[Groups(['event:list', 'event:read'])]
    private EventStatus $status = EventStatus::Draft;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $reminderSentAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['event:list', 'event:read'])]
    private ?User $organizer = null;

    /** @var Collection<int, Registration> */
    #[ORM\OneToMany(targetEntity: Registration::class, mappedBy: 'event', orphanRemoval: true)]
    private Collection $registrations;

    public function __construct()
    {
        $this->registrations = new ArrayCollection();
    }

    /** Value of the discriminator column, exposed in the API. */
    #[Groups(['event:list', 'event:read', 'registration:read'])]
    abstract public function getType(): string;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStartsAt(): ?\DateTimeImmutable
    {
        return $this->startsAt;
    }

    public function setStartsAt(\DateTimeImmutable $startsAt): static
    {
        $this->startsAt = $startsAt;

        return $this;
    }

    public function getEndsAt(): ?\DateTimeImmutable
    {
        return $this->endsAt;
    }

    public function setEndsAt(\DateTimeImmutable $endsAt): static
    {
        $this->endsAt = $endsAt;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getStatus(): EventStatus
    {
        return $this->status;
    }

    public function setStatus(EventStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function isPublished(): bool
    {
        return EventStatus::Published === $this->status;
    }

    public function getReminderSentAt(): ?\DateTimeImmutable
    {
        return $this->reminderSentAt;
    }

    public function setReminderSentAt(?\DateTimeImmutable $reminderSentAt): static
    {
        $this->reminderSentAt = $reminderSentAt;

        return $this;
    }

    public function getOrganizer(): ?User
    {
        return $this->organizer;
    }

    public function setOrganizer(User $organizer): static
    {
        $this->organizer = $organizer;

        return $this;
    }

    public function isOrganizedBy(User $user): bool
    {
        return null !== $this->organizer && $this->organizer->getId() === $user->getId();
    }

    /** @return Collection<int, Registration> */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    #[Groups(['event:list', 'event:read'])]
    public function getRegisteredCount(): int
    {
        return $this->registrations->count();
    }

    #[Groups(['event:list', 'event:read'])]
    public function getRemainingSeats(): ?int
    {
        return null === $this->capacity ? null : max(0, $this->capacity - $this->getRegisteredCount());
    }

    public function isFull(): bool
    {
        return 0 === $this->getRemainingSeats();
    }
}
